version: 2

references:
  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "presentation/build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - run:
          name: Run Code style
          command: ./gradlew ktlint

      - run:
          name: Run Unit test
          command: ./gradlew fullCoverageReport

      - run:
          name: Upload coverage report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: presentation/build/coverage-report
          destination: reports

      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: presentation/build/coverage-report
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples